

services:
  clickhouse:
    image: "altinity/clickhouse-server:24.12.2.20203.altinityantalya"
    container_name: clickhouse
    volumes:
      - ./chi-config.xml:/etc/clickhouse-server/config.d/proxy.xml
    depends_on:
      - nginx
  nginx:
    container_name: nginx
    image: ghcr.io/nginxinc/nginx-s3-gateway/nginx-oss-s3-gateway:latest
    env_file:
      - ./nginx-settings.env
    ports:
      - '8080:80'
    depends_on:
      - minio
  minio:
    image: bitnami/minio:2024.5.10-debian-12-r2
    restart: always
    ports:
      - "9010:9000"
      - "9001:9001"
    volumes:
      - "minio_data:/bitnami/minio/data"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DEFAULT_BUCKETS=default
volumes:
  minio_data:
    driver: local
